service: prize-ranking

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-offline

custom:
  serverless-offline:
    port: ${env:offline_app_port}

provider:
  name: aws
  runtime: nodejs10.x
  region: ${env:aws_region}
  profile: ${env:aws_profile}
  stage: ${env:stage}

functions:
  indexRanking:
    handler: src/services/ranking/handler.indexRanking
    events:
    - http:
        path: ranking
        method: get
        cors: true
  showUserScore:
    handler: src/services/ranking/handler.showUserScore
    events:
    - http:
        path: users/{username}/score
        method: get
        cors: true
  updateUserScore:
    handler: src/services/ranking/handler.updateUserScore
    events:
    - http:
        path: users/{username}/score/{score}
        method: put
        cors: true
  showUserCredits:
    handler: src/services/ranking/handler.showUserCredits
    events:
    - http:
        path: users/{username}/credits
        method: get
        cors: true
  assignWinnerPrize:
    handler: src/services/ranking/handler.assignWinnerPrize
    events:
    - http:
        path: winner-prize
        method: post
        cors: true