service: prize-ranking

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-offline

custom:
  serverless-offline:
    port: ${env:offline_port}

provider:
  name: aws
  runtime: nodejs10.x
  region: ${env:region}
  profile: ${env:profile}
  stage: ${env:stage}
