openapi: 3.0.0
servers:
  - url:  https://94hhu7cqel.execute-api.us-west-2.amazonaws.com/dev
info:
  description: This is a simple API to get and update user ranking.
  version: "1.0.0"
  title: Prize Ranking API
  contact:
    email: angel@pixan.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: Ranking Service
    description: Ranking calls.
paths:
  /ranking:
    get:
      tags:
        - Ranking Service
      summary: Get ranking.
      operationId: indexRanking
      description: Get ranking by current day, week or month, or since ever (default).
      parameters:
        - $ref: '#/components/parameters/pageParam'
        - $ref: '#/components/parameters/pageSizeParam'
        - $ref: '#/components/parameters/rankingModeParam'
      responses:
        '206':
          description: Paginated ranking list.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/RankingUser'
                  meta:
                    $ref: '#/components/schemas/PaginationMeta'
        '422':
          description: Some parameter is invalid.
  /users/{username}/score:
    get:
      tags:
        - Ranking Service
      summary: Get user score.
      operationId: showUserScore
      description: Get user score by passsing its id.
      parameters:
        - $ref: '#/components/parameters/usernameParam'
        - $ref: '#/components/parameters/rankingModeParam'
      responses:
        '200':
          description: User score.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: integer
                    example: 2560
        '404':
          description: User not found.
  /users/{username}/score/{points}:
    put:
      tags:
        - Ranking Service
      summary: Set user score.
      operationId: updateUserScore
      description: Set new user score if this is greater than current score.
      parameters:
        - $ref: '#/components/parameters/usernameParam'
        - in: path
          name: points
          description: New score, must be integer and greater than zero.
          required: true
          schema:
            type: integer
            example: 3000
      responses:
        '200':
          description: New user score. Note that if requested score is less than current score then it won't be affected and will return the old score.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: integer
                    example: 2560
        '422':
          description: New score is invalid.
  /users/{username}/credits:
    get:
      tags:
        - Ranking Service
      summary: Get user credits count.
      operationId: showUserCredits
      description: Ger total user credits until now.
      parameters:
        - $ref: '#/components/parameters/usernameParam'
      responses:
        '200':
          description: Total user credits.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: integer
                    example: 120
        '404':
          description: User not found.
  /assign-winner:
    post:
      tags:
        - Ranking Service
      summary: Assign credits to winner user(s) and reset corresponded ranking.
      operationId: assignWinnerPrize
      parameters:
        - $ref: '#/components/parameters/rankingModeParam'
      responses:
        '200':
          description: Operation successfully completed.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: integer
                    example: 120
  /users/{username}/exchange:
    post:
      tags:
        - Ranking Service
      summary: Exchange user's points by seeds or drops, 1 seed = 5 points, 1 drop = 1 point.
      operationId: exchangePoints
      parameters:
        - $ref: '#/components/parameters/usernameParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                uid:
                  type: string
                  example: 9Ma2Qj8b6
                currency:
                  type: string
                  enum: [seed, drop]
                amount:
                  type: number
                  example: 1
              required:
                - username
                - uid
                - currency
                - amount
      responses:
        '200':
          description: Operation successfully completed.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: number
                    example: 20
        '422':
          description: Some input field is invalid or exchange amount is not enought.
        '502':
          description: Proxy error (api where exchange amount is deposit).
components:
  parameters:
    pageParam:
      in: query
      name: page
      description: >
        Number of page you want to see.
      schema:
        type: number
        example: 1
    pageSizeParam:
      in: query
      name: page_size
      description: >
        Size of results you want peer page.
      schema:
        type: number
        example: 12
    usernameParam:
      in: path
      name: username
      description: Provider username.
      required: true
      schema:
        $ref: '#/components/schemas/username'
    rankingModeParam: 
      in: query
      name: mode
      description: Filter user score by specified time.
      required: true
      schema:
        type: string
        enum: [daily, weekly, monthly, always]
  schemas:
    PaginationMeta:
      type: object
      properties:
        page:
          type: number
          example: 1
        page_size:
          type: number
          example: 12
        has_more:
          type: boolean
          example: true
    RankingUser:
      type: object
      properties:
        username:
          $ref: '#/components/schemas/username'
        score:
          type: number
          example: 2560
        updated_at:
          $ref: '#/components/schemas/date'
    username:
      type: string
      format: string
      example: 'Master Chief 117'
    date:
      type: string
      format: 'ISO-8601'
      example: '2011-10-05T14:48:00.000Z'